[package]
name = "prima_pc"
version = "1.0.0"
edition = "2021"

[dependencies]
jni = "0.19.0"
chrono = "0.4"
dirs2 = "3.0.1"
futures = { version = "0.3.21", features = ["thread-pool"] }
rodio = "0.15.0"
async-recursion = "1.0.0"
once_cell = "1.10.0"

[lib]
crate-type = ["cdylib"]
